### ISSUE TITLE
Dev Task #1 

### ISSUE THREAD

**Issue by lucia2007** [lucia2007/bookwormkid#1]
As a **developer** I can **set up my project planning environments** so that I can **drive my project forwards and keep track of it's development**.

### Acceptance Criteria
- GitHub Projects Board created
- Figma file for wireframes created
- Lucidchart file for ERD created
- Get mentor approval and feedback

### Tasks
- [x]  Create GitHub Projects Board
- [x]  Create Figma File for wireframes
- [x]  Create Lucidchart for ERD
- [x]  PP4 first mentor meeting
