### ISSUE TITLE
US - Product Sorting Functionality

### ISSUE THREAD

**Issue by lucia2007** [lucia2007/bookwormkid#10]
As a **customer** I can **sort the products according to the price, category name and rating** so that I can **see the products sorting according to the chosen criterion**.

### Acceptance Criteria
1.  The products can be sorted according to price, rating and category name by clicking on the chosen criterion in the navbar.
2.  The select box reflects and displays the chosen criterion.
3.  Sorting in both asceding and descending order is possible.

### Tasks
- [x]  Enable sorting functionality through navbar, update links.
- [x]  Enable sorting through the select box.
- [x]  Connect select box and the navbar with javascript

**Comment by lucia2007** [comment]
Later during testing I realized name a-z, name z-a were not showing up in the sort window, so I fixed it.
