### ISSUE TITLE
US Sorting according to skill levels, special offers features

### ISSUE THREAD

**Issue by lucia2007** [lucia2007/bookwormkid#11]
As a **customer** I can **sort the products according to reading skill level, according to different special features** so that I can **quickly find the products I'm interested in**

### Acceptance Criteria
1.  When the user clicks on different skill levels, only books from the chosen category are displayed.
2.  When the user clicks on different special offers, only relevant products are show.
3.  The user can chose to view "all specials" at the same time.

### Tasks
- [x] Enable filtering according to skill level
- [x] Enable filtering according to special offer type
- [x] Display all special offers.
