### ISSUE TITLE
US - User Login/Logout Functionality

### ISSUE THREAD

**Issue by lucia2007** [lucia2007/bookwormkid#12]
As a **site user** I can **login in and logout of my account** so that I can **access personalized data, special features and keep my online activities safe**

### Acceptance Criteria
1.  The login icon is visible in navbar for a user that is not signed in.
2.  The logout option is available for the signed in user.
3.  Clicking on the login icon takes the user to the login page.

### Tasks
- [x]  Install django allauth, connect templates and views
- [x]  Add account icon to the navbar including the dropdown menu
- [x]  Style the icon and check responsiveness
