### ISSUE TITLE
US - View All Products

### ISSUE THREAD

**Issue by lucia2007** [lucia2007/bookwormkid#14]
As a **site user** I can **easily view all products offered** so that I can **choose a product that is most appealing to me**.

### Acceptance Criteria
1.  When clicking on "All books". all products are displayed.
2.  The number of displayed products changes according to the screen size.

### Tasks
- [x]  Create Product model in models.py
- [x]  Create all_product view in views.py
- [x]  Create urls.py
- [x]  Add new app into setting and project level urls
- [x]  Create products.html and adjust CSS
