### ISSUE TITLE
US -  Shopping Bag

### ISSUE THREAD

**Issue by lucia2007** [lucia2007/bookwormkid#16]
As a **customer** I can **choose the quantity of the product and add it to the shopping bag** so that I can **buy the product later**

### Acceptance Criteria
1.  Add to bag button visible
2.  Continue shopping button takes the user to the all products view
3.  A select window to indicate the product quanitty
4.  A shopping bag view with products details, quantity, subtotal and delivery fee is displayed when clicking on the shopping bag icon.

### Tasks
- [x] Add add to bag and continue shopping buttons
- [x] Add an input field for choosing the quanitty of the product
- [x]  Add the backened functionality for the quanitty to reflect changes in number
- [x]  Add shopping bag view, where the customer can see all the chosen items, their quantity and basic information.
- [x]  Calculate subtotal and delivery fee based on the size of the order.
