### ISSUE TITLE
US - Checkout

### ISSUE THREAD

**Issue by lucia2007** [lucia2007/bookwormkid#19]
As a **customer** I can **securely checkout the products in my shopping bag** so that I can **finish my purchase**.

### Acceptance Criteria
1.  User can easily add a chosen number of the chosen product to the shopping bag.
2.  The user can change the number of books in the shopping bag or remove the item completely.
3.  The user is informed through toasts about their actions (adding, removing, updating).
4.  The user's order is processed and displayed in Django Admin panel.

### Tasks
- [x]  Create and complete webhook_handler.py and webhooks.py for checkout with Stripe
- [x]  Implement the checkout logic
- [x]  Check webhooks if the payment is successful in Stripe
