### ISSUE TITLE
Dev Task - Set Up Development Environment

### ISSUE THREAD

**Issue by lucia2007** [lucia2007/bookwormkid#2]
As a **developer** I can **setup my project development environment** so that I can **start my project, install all dependencies and start working on documentation (readme)**.

### Acceptance Criteria
- GitHub repo based on CI Full template created
- Project baord connected to GitHub repo
- settings.py set up
- Django installed
- .gitignore file exists
- changes migrated
- project superuser created
- allauth installed and set up, including templates
- requirements frozen

### Tasks
- [x]  Setup GitHub repo using CI Full Template
- [x]  Connect repo with Projects board
- [x]  Ensure .gitignore file available, add env.py to it
- [x]  Install Django
- [x]  Setup settings.py
- [x]  Migrate changes
- [x]  Create project superuser
- [x]  Install and setup allAuth and templates
- [x]  Freeze requirements
