### ISSUE TITLE
US - User Notifications (Toasts)

### ISSUE THREAD

**Issue by lucia2007** [lucia2007/bookwormkid#20]
As a **customer** I can **view messages/toasts which inform me about my actions** so that I can **be sure that a certain action/choice took place**.

### Acceptance Criteria
1.  User sees notifications as they add, remove, or update the number of products in their shopping bag.
2.  User may/must dismiss the messages by clicking on "x" in the message container.
3.  User is informed if they are eligible for free delivery or if they need to increase their spend to be able to avail of it. 
4.  Messages are visible on all devices.
5. User is informed about their actions in connection with their accout registration, login, logout (part of allauth functionality).

### Tasks
- [x]  Create message container in HTML and add style in CSS.
- [x]  Create toasts folder with relevant message types.
- [x]  In checkout/views.py add relevant messages to different user actions (add, update, remove product from bag).
