### ISSUE TITLE
US - Wishlist

### ISSUE THREAD

**Issue by lucia2007** [lucia2007/bookwormkid#28]
As a **customer** I can **add desired products into my wishlist** so that I can **be reminded later which products were interesting for me**

### Acceptance Criteria
1.  The user can click on "Add to Wishlist"" button to add the chosen product to wishlist.
2.  The user is informed if the product had already been added to the wishlist previously.
3.  The user can delete an item from the wishlist.
4.  The user can choose to add the chosen product into shopping bag from the wishlist page.

### Tasks
- [x]  Create wishlist views, template and connect urls.
- [x]  Create wishlist functionality for adding and deleting products from the wishlist.
- [x]  Add "Add to wishlist" button to both all product view and the product detail pages.
- [x]  Add "Remove from Wishlist" and "Add to Bag" buttons to the wishlist template.
- [x]  Inform the user when their wishlist is empty.
