### ISSUE TITLE
US: Add Articles to the app (add, edit, delete functionality)

### ISSUE THREAD

**Issue by lucia2007** [lucia2007/bookwormkid#29]
As a **user** I can **read several interesting articles about why reading skills are important and how to encourage children to read** so that I can **understand the issue better**

### Acceptance Criteria
1.  Only a superuser can add an atricle (through admin panel)
2.  Only the user who entered the article can edit/delete the respective sample.
3.  The author of the article does not have to the superuser.
4.  The user is taken to the source of the article, if they are interested in more details.
5.  The superuser can create a draft of an article.
6.  The users can like/unlike the articles which is reflected in the number of likes and the color of the heart.

### Tasks
- [x]  Create article app, views and template. Connect urls.
- [x]  Add articles through the admin panel.
- [x]  Add the source and the author of each article to the model.
- [x]  Make edit/delete buttons accessible to Admin/superuser only.
- [x]  Add the like/unlike functionality, display number of likes and change the color of the heart.
