### ISSUE TITLE
User Story - Home Page

### ISSUE THREAD

**Issue by lucia2007** [lucia2007/bookwormkid#3]
As a **user** I can *access the application's home page** so that I can **understand the app's purpose and structure**.

### Acceptance Criteria 
1.  When the website loads, the user can see the home page.
2.  Home page navigation, hero picture and footer are in the correct place.

### Tasks
- [x]  Create base.html
- [x]  Create index.html and connect it to base.html
- [x]  Create header.html
- [x]  Create footer.html
- [x]  Create mobile navbar html
- [x]  Create main page navbar html
- [x]  Add favicon
