### ISSUE TITLE
US - Newsletter

### ISSUE THREAD

**Issue by lucia2007** [lucia2007/bookwormkid#30]
As a **user** I can **subscribe for a newsletter service** so that I can **be informed about any news, new development on the bookwormkid app**.

### Acceptance Criteria
1.  Newsletter functionality available through a button footer.
2.  Add a Subscribe button to the footer and take the user to a separate page to sign up for the newsletter.
3.  Get confirmation about being signed up.

### Tasks 
- [x] Create a newsletter app, template, view and connect urls.
- [x]  Add a button to footer which takes the user to a separate page, where they can sign up.
- [x]  Add messages to views, so that the user is informed about being signed up for the newsletter.
- [x]  Use mailchimp as the newsletter provider.
