### ISSUE TITLE
US: View all articles

### ISSUE THREAD

**Issue by lucia2007** [lucia2007/bookwormkid#32]
As a **user** I can **see all articles** so that I can **choose which one I am most interested in and educate myself on the top of the importance of reading**.

### Acceptace Criteria
1.  Create a all_articles view
2.  Add styling to the template for the articles to be displayed next to each other.
3.  Ensure the articles page is responsive.
4.  If the user is admin/superuser, add edit/delete buttons to the article cards.

### Tasks
- [x]  Create all_articles views and template.
- [x]  Add several articles through admin dashboard which are relevant to the app theme.
- [x]  Style the article cards and ensure responsivness. 
- [x]  Add edit/delete buttons for superusers.
