### ISSUE TITLE
US View Likes/Like/Unlike articles

### ISSUE THREAD

**Issue by lucia2007** [lucia2007/bookwormkid#33]
As a **signed in user** I can **like/unlike articles and be visually informed about my action** so that I can **express my views**.

### Acceptance Criteria
1.  A signed in user can click on a heart below a particular article to show their approval.
2.  A signed in user can click on the heart and "unlike" the article if they no longer agree with the contents.
3.  There is a number of likes displayed next to each heart to show how many registered users liked the article.
4.  The heart is solid when the user has liked the article and empy when unliked, or no action taken.

Tasks 
- [x]  Add like/unlike functionality to views and templates
- [x]  Alternate solid/empty heart to show if they article was liked.
- [x]  Add a counter of likes and display it next to the heart. 
- [x]  Use solid heart for liked and empty heart for not liked.
