### ISSUE TITLE
US Contact

### ISSUE THREAD

**Issue by lucia2007** [lucia2007/bookwormkid#35]
As a **user** I can **contact the store by filling in a form directly on the webpage** so that I **don't have to send an email through a different app**.

### Acceptance Criteria
1.  Contact button in the navbar takes the user to the correct page.
2.  The user can fill in the contact form.
3.  The user is informed about successul form submission.

### Tasks
- [x] Create Contact page template
- [x] Create a form for the user to fill in
- [x] Send email when the user has submitted the form
- [x]  Show message about successful form submission.

**Comment by lucia2007** [comment]
During testing I realized it would be a good UX, if a thank you page opened up after contact form submission, so I added it to my app.
