### ISSUE TITLE
US - Navigation

### ISSUE THREAD

**Issue by lucia2007** [lucia2007/bookwormkid#4]
As a **user** I can **locate the navigation area** so that I can **easily access different parts of the website**

### Acceptance Criteria
1.  The header is clearly distiguishable at the top of the page.
2.  The header sticks to the top of the page at all times.
3.  All icons take the user to the relevant page.
4.  The user is informed which page they are on.
5.  The site's logo takes the user to home page.
6.  The header is responsive.
7.  Search bar is present in NavBar.
8.  Footer displays relevant information and sticks to the bottom of the page

### Tasks
- [x] Add Bookworm Kid logo the NavBar
- [x] Create header.html
- [x] Create footer.html and make it stick to the bottom of the page
- [x] Link logo to index.html
- [x] Update base.html
- [x] Add search bar
- [x] Create relevant pages
- [x] Add links to NavBar items
- [x] Connect urls
- [x] Check responsivness
