### ISSUE TITLE
US - Visual confirmation for shopping bag/wishlist items

### ISSUE THREAD

**Issue by lucia2007** [lucia2007/bookwormkid#47]
As a **customer** I can **easily see if there is something in my wishlist or shopping bag** so that I can **be informed about my current and previous actions**.

### Acceptance Criteria
1.  When a customer add a product into the shopping bag, the shopping bag icon changes color to orange.
2.  If the customer deletes all the products from the shopping bag, the icon color changes back to black.
3.  When a customer add a product into wishlist, the wishlist icon changes color to orange.
4.  If the customer deletes all the products from the wishlist, the icon color changes back to black.

### Tasks
- [x] Add a conditional style around shopping bag icon in the navbar.
- [x] Add a conditional style around wishlist icon in the navbar.
- [x] Add css style for both icons.
