### ISSUE TITLE
US - Add age segmentation filtering

### ISSUE THREAD

**Issue by lucia2007** [lucia2007/bookwormkid#49]
As a **customer** I can **easily find books in a chosen age category** so that I **don't have to search all the products**.

### Acceptance Criteria
1.  A user is able to filter the books by age.
2.  Button to enable age segmentation are present on all products page and on age segment pages.

### Tasks
- [x]  Add new buttons for age categories 6-8, 9-10, 10-11, all ages to all products page.
- [x]  Add new buttons for age categories 6-8, 9-10, 10-11, all ages to the individual age range pages.
- [x]  Don't show the buttons on skill level pages.
