### ISSUE TITLE
US - Footer

### ISSUE THREAD

**Issue by lucia2007** [lucia2007/bookwormkid#5]
As a **user**, I can **access relevant information about the business, contact information and social media links without having to scroll back to the top of the page** so that I can **learn about terms and conditions, contact the eshop and follow the eshop online**.

### Acceptance Criteria
1. Footer is consistent through all the pages.
2. Footer sticks to the bottom of the page.
3. Footer contains relevant information (business details, terms and conditions, links to main pages,  contact infromation and social media links)
4.  All links, including social media open in a new tab.
5.  Footer is responsive.
6.  Mobile footer contains less information so it doesn't take up too much space. Relevant information is moved to the "hamburger" for small screens under HELP.

### Tasks
- [x] Update links to site navigation
- [x] Make the footer responsive
- [x] Move some of the information into the header 
- [x] Add contact information
