### ISSUE TITLE
US - Frequently asked questions

### ISSUE THREAD

**Issue by lucia2007** [lucia2007/bookwormkid#53]
As a **user** I can **easily find answers to frequently asked questions** so that I **don't have to call or write to the store owners to find out the information**.

### Acceptance Criteria
1.  A user can click on FAQ link in the footer and is taken to a page, where they can click on different questions and read the answers.
2.  The admin can add/edit or delete enquiries through the Bookstore management link in the navbar.

### Tasks
- [x]  Create a new enquiry app
- [x]  Set up CRUD functionality for superusers.
- [x]  Connect links and urls.
