### ISSUE TITLE
US - Add age segmentation for all product views and filters

### ISSUE THREAD

**Issue by lucia2007** [lucia2007/bookwormkid#54]
As a **user** I can **use age segmentation in combination with category or specials filters** so that I can **easily find an age appropriate book in the chosen subsegment**

### Acceptance Criteria
1.  Age filtering available on All products page.
2.  Age filtering available on skill level subsegment pages.
3.  Age filtering available on specials subsegment pages.

### Tasks
- [ ]  Refactor all specials pages and by age pages by defining new views.
- [ ]  Updated filters in html template to reflect the new filtering options.
- [ ]  Update the name of the name current segment for each page.
- [ ]  Update the name on the "all" button.
