### ISSUE TITLE
US - Optimize footer for small devices

### ISSUE THREAD

**Issue by lucia2007** [lucia2007/bookwormkid#55]
As a **user** I can **click on Help button in footer which contains all relevant links** so that I **don't have to scroll too far**.

### Acceptance Criteria
1.  On small and medium devices, collapsible Help button is displayed at the bottom of the footer.
2.  When clicking on the Help, links to shipping info, privacy policy and terms and conditions are accessible.

### Tasks
- [x]  Delete Help from the navbar
- [x]  Create a collapsible Help button using bootstrap
- [x]  Add terms&conditions
- [x]  Add privacy policy
- [x]  Update all links
- [x]  Check responsiveness
