### ISSUE TITLE
US - Add Terms and Conditions, Privacy Policy

### ISSUE THREAD

**Issue by lucia2007** [lucia2007/bookwormkid#56]
As a **user** I can **learn what the company's Terms and Conditions and Privacy Policy are** so that I can **understand my rights and obligations in connection to the store**

### Acceptance Criteria
1.  When the user clicks on Terms of Use in the footer, the document is displayed.
2.  The button works both on the mobile and larger devices.
3.  When the user clicks on Privacy Policy in the footer, the document is displayed.
4.  The button works both on the mobile and larger devices.

### Tasks
- [x]  Generate free Terms of Use on Termly
- [x]  Generate free Privacy Policy on Termply
- [x]  Create views, urls, connect button in the footer for both mobile version and the larger deviced
- [x]  Credit in Readme
