### ISSUE TITLE
US - Search Functionality

### ISSUE THREAD

**Issue by lucia2007** [lucia2007/bookwormkid#6]
As a **site user**, I can **enter keywords into the search** bar so that I can **search for a specific item**.

### Acceptance Criteria
1. Search bar is accessible in the navigation area. The search bar changes into a looking glass for smaller screens.
2. Placeholder text in the search field informs the user to enter text
3. Search function brings user to the searched item/items
4. The user can return to the top of the page by clicking on "back-to-top" button

### Tasks
- [x]  Add search bar to navigation area
- [x]  Adjust default bootstrap styling
- [x]  Add search functionality to view.py
- [x]  Test search bar
- [x]  Test responsivness
- [x]  Add placeholder text
- [x]  Add back to top button and relevant javascript
