### ISSUE TITLE
US - Sales price functionality

### ISSUE THREAD

**Issue by lucia2007** [lucia2007/bookwormkid#60]
As a **user** I can **buy products on sale** so that I can **save money and enjoy my shopping more**

### Acceptance Criteria
1.  When an item is on sale, the reduced price will show on both the product and product detail pages, the original price is crossed out.
2.  When the user puts the reduced item into the bag, the reduced price is taken into account and charged.

### Tasks
- [x]  Introduce final_price which depends on the fact if a product is on sale or not.
- [x]  Add final_price with property decorator into the product model.
- [x]  Update all relevant places, so that final_price is taken into account.
- [x]  Add the new sale price to the product and product detail pages. Cross out the original price, add the sales price in red.
