### ISSUE TITLE
US - Add double filtering for products according to different segments&age

### ISSUE THREAD

**Issue by lucia2007** [lucia2007/bookwormkid#61]
As a **user** I can **sort the products by age within any chosen subsegment** so that I can **quickly find an age appropriate book**.

### Acceptance Criteria
1.  Age buttons present on all product pages.
2.  If previous filtering applied, the age buttons will filter within the chosen category.

### Tasks
- [x]  Add button for age groups 6-8, 9-10 and 11-12.
- [x]  Refactor all of product pages (create new views) to be based on the main product page.
- [x]  Add double filtering to products.html template for different subsegments according to reading skills or if a products in the Specials.
- [x]  Update all page headings to the current one.
- [x]  Show which age button is being used at any given moment by applying class active on the buttons.
