### ISSUE TITLE
US - Make the chosen age parameter visually clear

### ISSUE THREAD

**Issue by lucia2007** [lucia2007/bookwormkid#65]
As a **user** I can **easily say if an age filter has been applied to the current template** so that I **don't have to study the product list for confirmation**.

### Acceptance criteria
1.  When the user clicks on a chosen age segment, or all products within the chosen segment, the relevant button is clearly highlighted.
2.  This feature is available for all types of product filtering no matter if its all products, segments by skill level or in the special category.

### Tasks 
- [x]  Add an if statement around the filters to show dark blue button when clicked and without bg-color when not chosen.
- [x]  Add this statement to all of the product filters.
- [x]  Make sure you don't get an error/warning for the usage of the if statements.
