### ISSUE TITLE
US - Bookstore Management

### ISSUE THREAD

**Issue by lucia2007** [lucia2007/bookwormkid#67]
A an **admin/superuser** I can access the Bookstore management page** so that I **can add/edit/delete Articles, Enquiries and Products without having to access the django admin**.

### Acceptance Criteria
1.  When an admin/superuser is signed in, they can access "Bookstore Management" page under their profile icon.
2.  Admin can add/edit/delete new product, articles, drafts.
3.  Admin can create drafts or articles and enquiries.
4.  Regular user or an unsigned user can see only published articles and enquries, not the drafts.

### Tasks
- [x]  Enable full CRUD functionality for Admin for Products, Articles and Enquiries.
- [x]  Enable saving drafts of articles and enquiries.
- [x]  Display only published articles and enquiries to other users (use Status=1)

**Comment by lucia2007** [comment]
At the mentor's suggestion I added restrictions around the bookstore management view, so that only a signed in admin user could access this link https://bookwormkid-c20568b2004e.herokuapp.com/bookstoremanagement/bookstoremanagement.
