### ISSUE TITLE
DT - Add products to the database

### ISSUE THREAD

**Issue by lucia2007** [lucia2007/bookwormkid#7]
As a **developer** I can **create a Category and Product model** so that I **can add products for the store to my database**.

### Acceptance Criteria
1. Products added to database
2. Products visible on website product view page
3. Products in a sustainable file so they can be reentered if needed.

### Tasks
- [x]  Create Category and Product models in Product app models.py
- [x]  Create admin view
- [x]  Create products.html
- [x]  Create product_detail.html
- [x]  Update urls.py and views.py
- [x]  Migrate changes
- [x]  Create a sustainable reusable uploadable file
- [x]  Update database with products

**Comment by lucia2007** [comment]
I tried to compress all of my images and to change them into the webp format, but some of them were so small, that I had to revert to their original size. I know this is not ideal and inconsistent, but for some of the books I couldn't find images of higher quality.
