### ISSUE TITLE
US - Wishlist visual confirmation

### ISSUE THREAD

**Issue by lucia2007** [lucia2007/bookwormkid#72]
As a **user** I can **clearly see that I already have a book in my wishlist** so that I don't **try to add it again**.

### Acceptance Criteria
1.  When a user adds a product to a wishlist, the heart color changes to solid and the button changes to Remove from Wishlist.
2.  This works on both the products.html and product_detail.html

### Tasks
- [x]  Update context processor
- [x]  Add an if statement around wishlist items in products
- [x]  Add an if statement around wishlist items in product_details
