### ISSUE TITLE
US - View Article Detail

### ISSUE THREAD

**Issue by lucia2007** [lucia2007/bookwormkid#73]
As a **user** I can **click on the article card** so that I can **read the article and see extra details**.

### Acceptance Criteria
1.  When user clicks on an article, they are taken to article_detail.html, where they can read the whole article.
2.  More details, including source are visible.
3.  A signed in user can click on the heart to like/unlike an article.

### Tasks
- [x]  Create article_detail view, connect urls, create template
- [x]  Add a heart icon for like/unlike functionality
- [x]  Add source and other details
