### ISSUE TITLE
US - Order Email Confirmation

### ISSUE THREAD

**Issue by lucia2007** [lucia2007/bookwormkid#74]
As a **customer** I can **receive an email after purchase** so that I can **confirm my purchase and keep a record of my order**.

### Acceptance Criteria
1.  Email is received by user with correct order information

### Tasks
- [x]  Setup email in settings.py
- [x]  Create email template forms to display order information
- [x]  Create checkout success views
