### ISSUE TITLE
USER STORY - Email Validation for Account

### ISSUE THREAD

**Issue by lucia2007** [lucia2007/bookwormkid#75]
As a **site user** I can **register my email and receive a validation link via email** so that I **can create an account to track my spending and purchases**.

### Acceptance Criteria
1. User receives email and email link allows validation
2. Validation succeeds and allows user to log in successfully

### Tasks

- [x]  Set up Gmail account for sending emails
- [x]  Set up App Password and connect to Heroku and settings.py
- [x]  Add Development variables for Email authentication

**Comment by lucia2007** [comment]
In the middle of my app development, my registration and email sending stopped working, because for some reason my password app in gmail got deleted. I had to add it again and change the password in Heroku. I hope this does not happen again, as it is out of my control.
