### ISSUE TITLE
US - View All Products

### ISSUE THREAD

**Issue by lucia2007** [lucia2007/bookwormkid#8]
As a **customer**, I can **easily scroll through all products** so that I can **see all the products the eshop offers".

### Acceptance Criteria
1. All books are visible when clicked on All Products
2. The books are arranged in a easily readable manner
3.  The number of books displayed changes depending on the screen size.

### Tasks
- [x]  urls.py
- [x]  views.py
- [x]  add products app to setting.py
- [x]  Populate products.html
- [x]  Populate product_detail.html
